### ISSUE TITLE
Explanation of project

### ISSUE THREAD

**Issue by k0d** [microsoft/jacdac-pico#1]
I know it's early in the development, but I'm trying to figure out how this will work. Will it be so the pico can act as a bridge and/or a brain? I tested the code from last week on my custom brain, it compiles...but I didn't get any console logs out. Should it show up as a usb device yet? or console over uart?

This looks really exciting anyway, and I hope to contribute to is when I understand more about the goals.

**Comment by pelikhan** [comment]
Sorry for the delay. The pico will be running DeviceScript, see https://microsoft.github.io/devicescript .
